folio-org/ui-erm-usage

- Jenkinsfile
Need to get this under CI so that it can be installed via `yarn` for `platform-erm` (and platforms in general).
> Added Jenkinsfile for CI builds

- src/components/HarvestingConfiguration/HarvestingConfigurationView.js
- src/components/HarvestingConfiguration/SushiCredentials/SushiCredentialsView.js
- src/components/UsageDataProviders/UsageDataProviderView.js
- src/settings/Aggregators/AggregatorDetail.js
- src/settings/Aggregators/AggregatorManager.js
- src/settings/DisplaySettings/DisplaySettings.js
- src/settings/DisplaySettings/index.js
- src/settings/index.js
- translations/ui-erm-usage/en.json
Can be used when presenting the app
> Add setting to hide sushi credentials in detail views

- translations/ui-erm-usage/ar.json
> Update translation strings as of 20190517T183537

- translations/ui-erm-usage/ar.json
> Update translation strings as of 20190828T124751

- translations/ui-erm-usage/zh_CN.json
> Update translation strings as of 20190909T193700

- translations/ui-erm-usage/it_IT.json
> Update translation strings as of 20190913T225241

- translations/ui-erm-usage/ja.json
> Update translation strings as of 20191101T131808

- translations/ui-erm-usage/it_IT.json
> Update translation strings as of 20191115T154823

- translations/ui-erm-usage/fr_FR.json
> Update translation strings as of 20200220T141728

- translations/ui-erm-usage/fr_FR.json
> Update translation strings as of 20200302T163727

- src/settings/Aggregators/AggregatorDetails.js
Make aggregator config accordion responsive to expand all and collapse all
> Bugfix: AggregatorConfig Accordion expand/collapse

- src/components/HarvestingConfiguration/HarvestingConfigurationView.js
- src/components/HarvestingConfiguration/VendorInfo/VendorInfoView.js
- src/components/ReportUpload/ReportUpload.js
- src/components/StartHarvesterButton/StartHarvesterButton.js
- src/components/Statistics/DownloadRange/DownloadRange.js
- src/components/Statistics/ReportButton/ReportButton.js
- src/components/Statistics/Statistics.js
- src/components/Statistics/StatisticsPerYear/StatisticsPerYear.js
- src/components/views/UDP.js
- src/settings/Aggregators/AggregatorDetails.js
- src/settings/Aggregators/AggregatorManager.js
- src/settings/Aggregators/DownloadCredentialsButton/DownloadCredentialsButton.js
- src/settings/PeriodicHarvesting/PeriodicHarvestingManager.js
- src/settings/index.js
> Use stripesConnect() HOC to connect components

- translations/ui-erm-usage/ja.json
> Update translation strings as of 20200413T183215

- translations/ui-erm-usage/zh_TW.json
> Update translation strings as of 20200513T135229

- translations/ui-erm-usage/zh_CN.json
> Update translation strings as of 20200615T161518

- package.json
- src/components/HarvestingConfiguration/HarvestingConfigurationForm.js
- src/components/HarvestingConfiguration/SushiCredentials/SushiCredentialsForm.js
customerId is not be required when harvestVia=aggregator, for harvestVia=sushi it is required
> [UIEUS-190] Customer id not required aggregator

- package.json
- src/components/StartHarvesterButton/StartHarvesterButton.js
- src/components/views/UDP.js
- src/settings/PeriodicHarvesting/PeriodicHarvestingForm.js
- src/settings/PeriodicHarvesting/PeriodicHarvestingManager.js
- test/bigtest/interactors/udp-details-page.js
- test/bigtest/tests/details-udp-test.js
PeriodicHarvestingForm is stripesFinalForm
> Bugfix: Selecting a date in harvester periodic settings crashes application

- translations/ui-erm-usage/ja.json
> Update translation strings as of 20201102T140138

- package.json
Thir PR upgrades devDependency of @folio/stripes-cli to v2.
> UIEUS-239: Upgrade stripes-cli to v2

- .gitignore
- src/components/HarvestingConfiguration/HarvestingConfigurationForm.js
- src/components/HarvestingConfiguration/SushiCredentials/SushiCredentialsForm.js
- src/components/HarvestingConfiguration/SushiCredentials/SushiCredentialsView.js
- test/bigtest/interactors/udp-edit-page.js
- test/bigtest/tests/create-udp-test.js
- translations/ui-erm-usage/en.json
This PR adds the field platform to the sushi credentials.
https://issues.folio.org/browse/UIEUS-240
> UIEUS-240: Add platform to sushi credentials

- src/components/ReportUpload/NonCounterUploadModal/NonCounterUploadModal.js
- test/bigtest/interactors/udp-details-page.js
- test/bigtest/tests/details-udp-test.js
This PR fixes the broken layout of non-counter upload modal.
https://issues.folio.org/browse/UIEUS-241
> UIEUS-241: Fix display of non-counter upload modal

- src/util/data/filterGroups.js
This PR fixes filtering of UDPs by tags.
https://issues.folio.org/browse/UIEUS-244
> UIEUS-244: Fix filtering by tags

- src/components/HarvestingConfiguration/VendorInfo/VendorInfoForm.js
- src/util/validate.js
https://issues.folio.org/browse/UIEUS-249
**Steps to Reproduce:**
Go to eUsage, create or edit a UPD
Enter a value, that is not a valid http or https URL into the field "Service URL"
**Expected Results:**
The field should turn red, and a text below should say "Invalid URL: http:// or https:// required!"
The user should not be able to save.
> UIEUS-249-validation-for-field-serviceUrl add required url validation

- src/components/Statistics/Counter/ReportInfo/ReportInfo.js
- translations/ui-erm-usage/en.json
https://issues.folio.org/browse/UIEUS-252
> UIEUS-252-move-trailing-space

- src/components/Custom/CustomStatistics.test.js
- src/components/Custom/InfoButton/InfoButton.js
- src/components/Custom/InfoButton/InfoButton.test.js
- test/jest/__mock__/stripesCore.mock.js
- test/jest/server-handlers.js
This PR adds RTL/Jest tests for \<CustomStatistics\> and \<InfoButton\>.
> Add more tests

- Jenkinsfile
- package.json
- test/jest/babel.config.js
Refs. https://issues.folio.org/browse/UIEUS-258
> UIEUS-258: Compile Translation Files into AST Format

- src/components/Custom/CustomReportInfo/CustomReportInfoFile.js
- src/components/Custom/CustomReportInfo/CustomReportInfoLink.js
- src/components/Custom/CustomReportInfo/ReportInfoHeader.js
- src/components/Custom/CustomStatistics.js
- src/components/Custom/CustomStatistics.test.js
- src/components/Custom/InfoButton/InfoButton.js
- src/components/Custom/InfoButton/InfoButton.test.js
- src/components/DeleteStatisticsModal/DeleteStatisticsModal.js
- src/components/ReportUpload/NonCounterUpload/NonCounterUploadModal.js
- src/components/views/UDP.js
- src/routes/UDPCreateRoute.js
- src/routes/UDPEditRoute.js
- src/routes/components/withReportHandlers.js
- src/settings/PeriodicHarvesting/PeriodicHarvestingForm.js
Refs. https://issues.folio.org/browse/UIEUS-263
> UIEUS-263: Use @folio/stripes exports instead private paths

- CHANGELOG.md
- src/components/views/UDP.js
> Add a pluggable surface of type `ui-agreements-extension`

- src/components/views/UDP.js
https://issues.folio.org/browse/UIEUS-270
> UIEUS-270: Remove isWithinScope

- src/components/HarvestingConfiguration/Fields/HarvestingViaSelect.js
- src/components/HarvestingConfiguration/HarvestingConfigurationForm.js
- src/components/views/UDPForm.test.js
https://issues.folio.org/browse/UIEUS-274
> UIEUS-274: Updating required field customerId

- src/components/HarvestingConfiguration/AggregatorInfo/AggregatorInfoView.js
- src/components/HarvestingConfiguration/HarvestingConfigurationView.test.js
https://issues.folio.org/browse/UIEUS-276
> UIEUS-276: check permission for aggregator link

- package.json
Adds missing permissions
* `ermusageharvester.impl.get`
* `configuration.entries.item.put`
> UIEUS-287, UIEUS-288 Add missing permissions

- README.md
Adapt copyright in README to 2022
> adapt-copyright

- src/components/views/UDPForm.js
- src/routes/UDPCreateRoute.js
https://issues.folio.org/browse/UIEUS-310
> UIEUS-310: Save button active after change

- src/components/HarvestingConfiguration/HarvestingConfigurationForm.js
- src/components/HarvestingConfiguration/VendorInfo/VendorInfoForm.js
- src/components/UDPInfo/UDPInfoForm.js
- src/components/views/UDPForm.css
- src/util/sharedStyles/form.css
https://issues.folio.org/browse/UIEUS-315
> UIEUS-315-reorder-edit-create-screen

- CHANGELOG.md
- src/components/StartHarvesterModal/StartHarvesterModal.js
- src/settings/StartHarvester/StartHarvester.js
- translations/ui-erm-usage/en.json
Updates the message that is displayed when harvesting is started for a tenant or provider.
> UIEUS-331-harvester-started-message

- CHANGELOG.md
- package.json
Increase major version and update CHANGELOG
> UIEUS-337 Upgrade React to v18

- CHANGELOG.md
- src/components/ReportUpload/FileUploader.js
- src/components/views/UDP.js
* Use noClick prop on Dropzone to prevent the file open dialog from showing up twice
* Cosmetic change to component structure in `UDP.js`
> UIEUS-344 Fix file open dialog showing twice

- CHANGELOG.md
- src/components/Counter/DownloadRange/DownloadRange.js
- src/components/JobsView/JobsView.js
- src/components/ReportUpload/CounterUpload/CounterUpload.test.js
- src/components/ReportUpload/NonCounterUpload/NonCounterUpload.test.js
- src/components/views/UDP.js
- src/components/views/UDP.test.js
- src/components/views/UDPForm.js
- src/components/views/UDPs.js
- src/settings/Aggregators/AggregatorForm.js
- src/settings/PeriodicHarvesting/PeriodicHarvestingManager.js
- src/settings/StartHarvester/StartHarvester.js
https://issues.folio.org/browse/UIEUS-349
> UIEUS-349-remove-deprecated-pane-properties

- CHANGELOG.md
- src/components/JobsView/JobsView.test.js
https://folio-org.atlassian.net/browse/UIEUS-360
> UIEUS-360: fix-bug-in-JobView-test

- CHANGELOG.md
- src/commands.js
- src/index.js
https://folio-org.atlassian.net/browse/UIEUS-364
> UIEUS-364: Show-overview-keyboard-shortcuts

- CHANGELOG.md
- package.json
- src/components/HarvestingConfiguration/Fields/ReportReleaseSelect.js
- src/components/HarvestingConfiguration/HarvestingConfigurationForm.js
- src/components/HarvestingConfiguration/SelectedReports/SelectedReportsForm.js
- src/components/HarvestingConfiguration/SushiCredentials/SushiCredentialsForm.js
- src/components/views/UDPForm.test.js
- src/routes/UDPCreateRoute.js
- src/util/data/reportReleaseOptions.js
- test/fixtures/udp.js
- test/fixtures/udps.js
This reverts commit d03b0ad634dd2697af326f12a961de6142d2ff65.
> Revert "UIEUS-370: Update to usage data providers 3.0 (#484)"

- CHANGELOG.md
- src/components/Counter/ReportInfoButton/ReportInfoButton.js
- src/components/Custom/InfoButton/InfoButton.js
- src/components/Custom/InfoButton/InfoButton.test.js
- translations/ui-erm-usage/en.json
https://folio-org.atlassian.net/browse/UIEUS-376
> UIEUS-376: Fix heading deleting single counter report

- .github/workflows/ui.yml
Run GA workflow on every branch
> Run GA workflow on every branch

- CHANGELOG.md
- package.json
https://folio-org.atlassian.net/browse/UIEUS-378
See https://github.com/folio-org/mod-erm-usage/pull/184
> Update counter-reports interface to 4.0

- CHANGELOG.md
- package.json
https://folio-org.atlassian.net/browse/UIEUS-379
https://github.com/folio-org/mod-erm-usage/pull/185 requires adjustments to permissions and ` aggregator-settings` interface version.
> [UIEUS-379] Adjust permissions and interface versions

- CHANGELOG.md
- package.json
https://folio-org.atlassian.net/browse/UIEUS-380
See https://github.com/folio-org/mod-erm-usage-harvester/pull/182
> [UIEUS-380] Adjust permissions and interface versions

- CHANGELOG.md
- package.json
- translations/ui-erm-usage/en.json
https://folio-org.atlassian.net/browse/UIEUS-385
* Rename permissions
* Update translation for permissions
> [UIEUS-385] Update translation for permissions

- CHANGELOG.md
- package.json
Merge Release v10.0.1 into master
> merge b10.1

- translations/ui-erm-usage/en.json
https://folio-org.atlassian.net/browse/UIEUS-404
* Updates text displayed in the upload form for counter reports
> [UIEUS-404] Update text in upload form for manual upload for COUNTER 5.1

- .eslintrc
- CHANGELOG.md
- yarn.lock
https://folio-org.atlassian.net/browse/UIEUS-405
> [UIEUS-405] Release v11.0.0

- CHANGELOG.md
- src/components/Counter/ReportInfoButton/ReportInfoButton.js
- src/components/Counter/ReportInfoButton/ReportInfoButton.test.js
https://folio-org.atlassian.net/browse/UIEUS-225
> UIEUS-225: Flag uploaded reports

- CHANGELOG.md
- src/components/Counter/ReportInfo/ReportInfo.js
- src/components/Counter/ReportInfo/ReportInfo.test.js
- translations/ui-erm-usage/en.json
https://folio-org.atlassian.net/browse/UIEUS-367
> UIEUS-367: Add section for error

- CHANGELOG.md
- package.json
- src/components/HarvestingConfiguration/SushiCredentials/SushiCredentialsView.js
- src/routes/UDPViewRoute.js
- src/settings/Aggregators/AggregatorDetails.js
- src/settings/DisplaySettings/DisplaySettings.js
- src/settings/DisplaySettings/DisplaySettings.test.js
- src/settings/HarvesterLogs/HarvesterLogsSettings.js
- src/settings/HarvesterLogs/HarvesterLogsSettings.test.js
- src/settings/MaxFailedAttempts/MaxFailedAttempts.js
- src/settings/MaxFailedAttempts/MaxFailedAttempts.test.js
- src/util/constants.js
- test/jest/helpers/withReduxForm.js
https://folio-org.atlassian.net/browse/UIEUS-387
> [UIEUS-387] Migrate settings from `mod-configuration` to `mod-settings`

- CHANGELOG.md
- src/settings/Aggregators/AggregatorForm.js
- src/settings/Aggregators/AggregatorForm.test.js
- src/settings/Aggregators/DisplayContactsForm.js
https://folio-org.atlassian.net/browse/UIEUS-411
> UIEUS-411: Fix settings aggregator form

- CHANGELOG.md
* Update CHANGELOG by merging `v11.0.1`
> Merge v11.0.1

- CHANGELOG.md
- src/components/UDPFilters/UDPFilters.js
- src/components/UDPHeader/UDPHeader.js
- src/components/UDPInfo/UDPInfoForm.js
- src/components/views/UDPs.test.js
- src/util/data/filterGroups.js
- translations/ui-erm-usage/en.json
https://folio-org.atlassian.net/browse/UIEUS-391
> UIEUS-391: Add provider status filter

- src/components/views/UDPs.js
https://folio-org.atlassian.net/browse/UIEUS-391
In the previous pull request I missed adapting the initial filter.
> UIEUS-391: Adapt default filter

- CHANGELOG.md
- src/components/HarvestingConfiguration/HarvestingConfigurationForm.js
- src/components/HarvestingConfiguration/VendorInfo/VendorInfoForm.js
https://folio-org.atlassian.net/browse/UIEUS-417
> UIEUS-417: Re-order elements in upd form

- CHANGELOG.md
- src/components/HarvestingConfiguration/Fields/HarvestingStatusSelect.js
- src/components/HarvestingConfiguration/HarvestingConfigurationForm.js
- src/components/UDPInfo/UDPInfoForm.js
- src/components/views/UDPForm.js
- src/components/views/UDPForm.test.js
- src/routes/UDPCreateRoute.js
- src/util/data/statusOptions.js
- translations/ui-erm-usage/en.json
https://folio-org.atlassian.net/browse/UIEUS-418
> UIEUS-418: Check combination harvester provider status

- CHANGELOG.md
- src/components/HarvestingConfiguration/Fields/HarvestingEndField.js
- src/components/HarvestingConfiguration/Fields/HarvestingStartField.js
- src/components/HarvestingConfiguration/HarvestingConfigurationForm.js
- src/components/views/UDPForm.test.js
- src/util/Monthpicker/Monthpicker.js
- src/util/validate.js
https://folio-org.atlassian.net/browse/UIEUS-416
> UIEUS-416: Use monthpicker for harvesting date

- CHANGELOG.md
- src/components/views/UDPs.js
https://folio-org.atlassian.net/browse/UIEUS-450
> UIEUS-450: Change default filters

- CHANGELOG.md
- src/components/Counter/ReportInfo/ReportInfo.js
- src/components/Counter/ReportInfo/ReportInfo.test.js
- src/components/HarvestingConfiguration/HarvestingConfigurationView.js
- src/components/HarvestingConfiguration/SushiCredentials/SushiCredentialsForm.js
- src/components/HarvestingConfiguration/SushiCredentials/SushiCredentialsView.js
- src/components/HarvestingConfiguration/VendorInfo/VendorInfoView.js
- src/settings/DisplaySettings/DisplaySettings.test.js
- src/util/data/filterGroups.js
- src/util/data/harvestingViaOptions.js
- translations/ui-erm-usage/en.json
https://folio-org.atlassian.net/browse/UIEUS-451
> UIEUS-451: Rename sushi

- src/components/Counter/DownloadRange/DownloadRange.js
- src/components/Counter/DownloadRange/DownloadRange.test.js
- src/components/Counter/utils.js
- src/components/Counter/utils.test.js
Reverts folio-org/ui-erm-usage#574
> Revert "UIEUS-458: Unique value for select add report type for download"

- CHANGELOG.md
- src/routes/UDPsRoute.js
https://folio-org.atlassian.net/browse/UIEUS-467
> UIEUS-467: Fix tags error
